version: 'minty.abcxyz.dev/v2'

rule:
  if: |-
    assertion.iss == issuers.github &&
    assertion.repository_owner_id == '93787867' &&
    assertion.repository_id == '767194578'

scope:
  teamlink:
    rule:
      if: |-
        assertion.workflow_ref.startsWith("abcxyz/team-link/.github/workflows/sync.yml") &&
        assertion.ref == 'refs/heads/main'
    repositories:
      - 'team-link'
    permissions:
      members: 'write'
  # TODO: remove this rule once the github sso development is done.
  teamlink-dev:
    rule:
      if: |-
        assertion.workflow_ref.startsWith("abcxyz/team-link/.github/workflows/sync.yml") &&
        assertion.ref == 'refs/heads/sailorlqh/sso_poc'
    repositories:
      - 'team-link'
    permissions:
      members: 'write'
  create-tag:
    rule:
      if: |-
        assertion.job_workflow_ref == "abcxyz/pkg/.github/workflows/create-tag.yml@refs/heads/main" &&
        assertion.workflow_ref.startsWith("abcxyz/team-link/.github/workflows/create-tag.yml") &&
        assertion.event_name == 'workflow_dispatch'
    repositories:
      - 'team-link'
    permissions:
      contents: 'write'
