version: 'minty.abcxyz.dev/v2'

rule:
  if: |-
    assertion.iss == issuers.github &&
    assertion.repository_owner_id == '93787867' &&
    assertion.repository_id == '767194578' &&
    ( assertion.ref == 'refs/heads/main' || assertion.ref == 'refs/heads/sso_poc' )

scope:
  teamlink:
    rule:
      if: |-
        assertion.workflow_ref.startsWith("abcxyz/team-link/.github/workflows/sync.yml")
    repositories:
      - 'team-link'
    permissions:
      members: 'write'
