mappings: [
  {
    # this team only has Qinhang
    google_group: {
      group_id: "groups/04f1mdlm2alv5ca"
    }
    git_hub_team: {
      # qh-org
      org_id: 145597256
      # test-everyone
      team_id: 11735575
    }
  }
]
