# Copyright 2024 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'Sync GoogleGroups to GitHub Membership'

on:
  push:
  workflow_dispatch:
    inputs:
      destinationToken:
        type: 'string'
        description: 'token for your target system'
        required: true

permissions:
  contents: 'read'
  id-token: 'write'

# Do not cancel in progress to prevent half baked release.
concurrency:
  group: 'team-link-${{ github.head_ref || github.ref }}'

env:
  WIF_SERVICE_ACCOUNT: 'github-automation-bot@gha-team-link-a-bc970e.iam.gserviceaccount.com'
  WIF_PROVIDER: 'projects/426803670395/locations/global/workloadIdentityPools/github-automation/providers/team-link-a'

jobs:
  run_sync:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11' # ratchet:actions/checkout@v4
      - id: 'setup-go'
        uses: 'actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7' # ratchet:actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: 'Mint Token'
        id: 'mint-token'
        uses: 'abcxyz/github-token-minter/.github/actions/mint-token@main' # ratchet:exclude
        with:
          wif_provider: '${{ vars.TOKEN_MINTER_WIF_PROVIDER }}'
          wif_service_account: '${{ vars.TOKEN_MINTER_WIF_SERVICE_ACCOUNT }}'
          service_audience: '${{ vars.TOKEN_MINTER_SERVICE_AUDIENCE }}'
          service_url: '${{ vars.TOKEN_MINTER_SERVICE_URL }}'
          requested_permissions: |-
            {
              "scope": "teamlink",
              "repositories": ["team-link"],
              "permissions": {
                "members": "write"
              }
            }
      - name: 'export github token'
        id: 'export_gh_token'
        run: |-
          echo "TEAM_LINK_GITHUB_TOKEN=${{ steps.mint-token.outputs.token }}" >> $GITHUB_OUTPUT
      - name: 'authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@55bd3a7c6e2ae7cf1877fd1ccb9d54c0503c457c' # ratchet:google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ env.WIF_PROVIDER }}'
          service_account: '${{ env.WIF_SERVICE_ACCOUNT }}'
          create_credentials_file: true
      # TODO: change this from directly run go to run a binary after setting up release.
      - name: 'run teamlink sync'
        run: |
          export TEAM_LINK_GITHUB_TOKEN='${{ steps.export_gh_token.outputs.TEAM_LINK_GITHUB_TOKEN }}'
          go run cmd/tlctl/main.go sync run \
            -m mappings.textproto \
            -c teamlink_config.textproto
